### ISSUE TITLE
undefined 'slice'

### ISSUE THREAD

**Issue by elieobeid7** [brunoscopelliti/poker-deck#1]
Copy pasting the example in the readme file, there seems to be an error with the library

```
/node_modules/poker-has/lib/utils/sort-by-rank.js:14
  (cards) => cards.slice()
                   ^

TypeError: Cannot read property 'slice' of undefined

```

**Comment by brunoscopelliti** [comment]
That's hardly a problem with `poker-deck`.

This probably should be opened on `poker-has` module. It would be useful if you can attach the entire stacktrace, and more info on the scenario.

Closing here, since this is not a problem of `poker-deck`
